import type { Metadata } from "next";
import "../globals.css";
import { ReactNode } from "react";
import {ClerkProvider} from '@clerk/nextjs'
import Header from "@/components/layout/Header";


export const metadata: Metadata = {
  title: "Sonny Ecommerce",
  description: "Generated by create next app",
};
const RootLayout=({
  children,
}: Readonly<{
  children: ReactNode;
}>)=> {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body className="">
          <Header />
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
export default RootLayout;